# Generated by Django 5.2.7 on 2026-03-07 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('name', models.CharField(choices=[('Cairo', 'Cairo'), ('Alexandria', 'Alexandria'), ('Aswan', 'Aswan'), ('Luxor', 'Luxor')], max_length=200)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('1', 'children'), ('2', 'interior'), ('3', 'bones'), ('4', 'the heart'), ('5', 'eyes'), ('6', 'nose'), ('7', 'women'), ('8', 'utensils'), ('9', 'surgery'), ('10', 'tract')], max_length=200, unique=True)),
                ('floor', models.CharField(choices=[('1', 'First'), ('2', 'Second'), ('3', 'Third'), ('4', 'Fourth'), ('5', 'Fifth'), ('6', 'Sixth'), ('7', 'Seventh'), ('8', 'Eighth'), ('9', 'Ninth'), ('10', 'Tenth')], max_length=20)),
                ('phone', models.CharField(max_length=11, unique=True)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.PositiveIntegerField()),
                ('area', models.CharField(blank=True, max_length=150, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Patients',
                'permissions': [('can_view_patient', 'can_view_patient'), ('can_add_patient', 'can_add_patient'), ('can_edit_patient', 'can_edit_patient'), ('can_delete_patient', 'can_delete_patient')],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(max_length=11, unique=True)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('address', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departs.departments')),
            ],
            options={
                'db_table': 'Doctors',
                'managed': True,
                'unique_together': {('name', 'part')},
            },
        ),
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detect', models.CharField(choices=[('1', 'normal'), ('2', 'urgent'), ('3', 'consultation')], default='normal', max_length=50)),
                ('detect_value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('paid_stat', models.BooleanField(default=False, max_length=10)),
                ('status', models.CharField(choices=[('1', 'OnGoing'), ('2', 'Completed'), ('3', 'Cancelled')], max_length=50)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='departs.doctors')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departs.patients')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_type', models.CharField(choices=[('1', 'cash'), ('2', 'visa'), ('3', 'cheque'), ('4', 'bank')], default='1', max_length=30)),
                ('paid_date', models.DateField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('appoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departs.appointments')),
            ],
            options={
                'ordering': ['paid_date'],
            },
        ),
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('1', 'saturday'), ('2', 'sunday'), ('3', 'monday'), ('4', 'tuesday'), ('5', 'wednesday'), ('6', 'thursday'), ('0', 'friday')], max_length=20)),
                ('available', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='departs.doctors')),
            ],
            options={
                'ordering': ['day'],
                'unique_together': {('day', 'doctor')},
            },
        ),
    ]
